# Generated by Django 5.0.3 on 2024-03-17 01:45

import users.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_location_state_location_zip_code_profile_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(null=True, upload_to=users.utils.user_upload_directory_path),
        ),
    ]
